/**
 * Session Store
 *
 * Manages the current storytelling session state including:
 * - Session metadata (id, timestamps, status)
 * - Player information
 * - Current scene state
 * - Transcript history
 * - LLM configuration
 *
 * Uses Svelte writable store for reactive state management with localStorage persistence
 */

import { writable } from 'svelte/store';
import {
  saveSessionToStorage,
  loadSessionFromStorage,
  setActiveSession,
  getActiveSessionId,
  clearActiveSession
} from '../utils/storage';

export interface Player {
  name: string;
  bio: string;
}

export interface TranscriptEntry {
  id: string;
  t: string; // ISO timestamp
  speaker: 'DM' | 'Player';
  playerName: string;
  text: string;
}

export interface LLMConfig {
  model: string;
  seed: number;
}

// ===== Scene-Based Architecture Types =====

/**
 * Represents a way to complete a scene
 */
export interface SceneExit {
  id: string;
  description: string;          // Internal description of exit
  condition: string;            // What needs to happen
  requiresRoll: boolean;        // Does this exit need a dice roll?
  difficulty?: number;          // If roll required (1-6 target)
}

/**
 * Represents a single interaction within a scene
 */
export interface SceneInteraction {
  id: string;
  timestamp: string;
  speaker: 'DM' | 'Player';
  playerName?: string;
  text: string;
  rollResult?: number;          // If this was a roll response
  rawResponse?: string;         // Raw JSON response from LLM (for DM only)
}

/**
 * Represents a dice roll opportunity in the scene
 */
export interface RollOpportunity {
  id: string;
  description: string;          // What the roll is for
  difficulty: number;           // Target number (1-6)
  exitId?: string;              // Associated exit if any
  resolved: boolean;
  result?: number;
  success?: boolean;
}

/**
 * Scene status lifecycle
 */
export type SceneStatus = 'setup' | 'active' | 'complete' | 'summarized';

/**
 * Complete scene definition
 */
export interface SceneDefinition {
  // Scene Identity
  id: string;
  number: number;
  title: string;
  
  // Scene Content (generated by LLM)
  setting: string;              // Where the scene takes place
  situation: string;            // What's happening
  internalGoal: string;         // Hidden objective (not shown to players)
  possibleExits: SceneExit[];   // Ways to complete the scene
  
  // Scene State
  status: SceneStatus;
  startedAt: string;
  completedAt?: string;
  
  // Interaction Tracking
  interactions: SceneInteraction[];  // Only this scene's turns
  rollOpportunities: RollOpportunity[];
  
  // Completion
  exitTaken?: string;           // Which exit was used
  summary?: string;             // Generated summary after completion
}

/**
 * Compressed summary of a completed scene
 */
export interface SceneSummary {
  sceneNumber: number;
  title: string;
  summary: string;              // Compressed narrative
  keyEvents: string[];          // Important moments
  itemsGained?: string[];       // Items/abilities acquired
  locationEnd: string;          // Where players ended up
  characterDevelopment?: string; // How characters grew
  timestamp: string;
}

/**
 * Story context for overall narrative
 */
export interface StoryContext {
  theme: string;
  overallGoal: string;          // Main story objective
  completedScenes: SceneSummary[];
}

/**
 * Response from LLM during scene play
 */
export interface SceneResponse {
  say: string;
  ask: string;
  needRoll: boolean;
  rollPurpose?: string;
  rollDifficulty?: number;
  sceneComplete: boolean;
  exitTaken?: string;
  storyComplete?: boolean;      // NEW: Indicates entire story should end
  storyResolution?: string;     // NEW: How the overall goal was achieved
}

/**
 * Scene setup response from LLM
 */
export interface SceneSetupResponse {
  title: string;
  setting: string;
  situation: string;
  internalGoal: string;
  possibleExits: Omit<SceneExit, 'id'>[];
  openingNarration: string;
  openingQuestion: string;
}

/**
 * Scene summary response from LLM
 */
export interface SceneSummaryResponse {
  summary: string;
  keyEvents: string[];
  itemsGained?: string[];
  locationEnd: string;
  characterDevelopment?: string;
}

// ===== Two-Tier Story State =====

export interface StoryPlan {
  currentObjective: string;
  upcomingChallenges: string[];
  themeElements: string[];
}

export interface StoryState {
  theme: string;
  overallGoal: string;
  targetSceneCount: number;
  currentPhase: 'beginning' | 'middle' | 'climax' | 'resolution';
  storyPlan: StoryPlan;
}

// ===== Updated Session Interface =====

export interface Session {
  version: number;
  id: string;
  createdAt: string;
  updatedAt: string;
  status: 'active' | 'completed' | 'abandoned';
  totalTurns: number;
  lastSpeaker: 'DM' | 'Player';
  audioEnabled: boolean;
  theme: string;
  players: Player[];
  heartsTrackedPhysically: boolean;
  
  // Two-Tier Story Management
  storyState: StoryState;
  
  // Scene Management
  currentSceneId: string;
  scenes: SceneDefinition[];
  storyContext: StoryContext;
  
  // Legacy transcript (kept for backward compatibility)
  transcript: TranscriptEntry[];
  
  llm: LLMConfig;
  
  // App State Resumption
  appState?: {
    turnState: string;  // Current TurnController state
    showDiceRoller?: boolean;
    currentRollDifficulty?: number;
    pendingDirective?: any;  // SceneDirective waiting to be processed
    lastPlayerInput?: string;  // Last player input (for resuming from thinking state)
    lastStateTimestamp?: string;
  };
}

// Default session state
const defaultSession: Session = {
  version: 3,
  id: '',
  createdAt: '',
  updatedAt: '',
  status: 'active',
  totalTurns: 0,
  lastSpeaker: 'DM',
  audioEnabled: true,
  theme: '',
  players: [],
  heartsTrackedPhysically: true,
  storyState: {
    theme: '',
    overallGoal: '',
    targetSceneCount: 10,
    currentPhase: 'beginning',
    storyPlan: {
      currentObjective: '',
      upcomingChallenges: [],
      themeElements: [],
    },
  },
  currentSceneId: '',
  scenes: [],
  storyContext: {
    theme: '',
    overallGoal: '',
    completedScenes: [],
  },
  transcript: [],
  llm: {
    model: 'anthropic/claude-3-haiku',
    seed: 0,
  },
  appState: {
    turnState: 'idle',
  },
};

// Maximum transcript entries to keep (from Plan.md line 197)
const MAX_TRANSCRIPT_ENTRIES = 50;

/**
 * Generate a UUID v4
 */
function generateUUID(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

/**
 * Session Store Class
 * Uses Svelte writable store for reactive state management
 */
class SessionStore {
  // Reactive state using Svelte writable store
  private _store = writable<Session>(defaultSession);
  private _session: Session = defaultSession;

  constructor() {
    // Subscribe to store updates to keep _session in sync
    this._store.subscribe(value => {
      this._session = value;
    });
  }

  /**
   * Get current session (reactive)
   */
  get current(): Session {
    return this._session;
  }

  /**
   * Subscribe to session changes
   */
  subscribe = this._store.subscribe;

  /**
   * Create a new session with initial state
   * @param theme - The story theme (e.g., "Knights and Dragons")
   * @param players - Array of player objects with name and bio
   * @returns The newly created session
   */
  createSession(theme: string, players: Player[]): Session {
    const now = new Date().toISOString();
    const sessionId = generateUUID();

    const newSession: Session = {
      version: 3,
      id: sessionId,
      createdAt: now,
      updatedAt: now,
      status: 'active',
      totalTurns: 0,
      lastSpeaker: 'DM',
      audioEnabled: true,
      theme,
      players,
      heartsTrackedPhysically: true,
      storyState: {
        theme,
        overallGoal: `Complete the ${theme} adventure`,
        targetSceneCount: 10,
        currentPhase: 'beginning',
        storyPlan: {
          currentObjective: '',
          upcomingChallenges: [],
          themeElements: [],
        },
      },
      currentSceneId: '',
      scenes: [],
      storyContext: {
        theme,
        overallGoal: `Complete the ${theme} adventure`,
        completedScenes: [],
      },
      transcript: [],
      llm: {
        model: 'anthropic/claude-3-haiku',
        seed: Math.floor(Math.random() * 1000000),
      },
    };

    this._store.set(newSession);
    this.saveSession();
    setActiveSession(sessionId);

    return newSession;
  }

  /**
   * Load an existing session from localStorage
   * @param sessionId - The session ID to load
   * @returns true if session was loaded successfully
   */
  loadSession(sessionId: string): boolean {
    const loadedSession = loadSessionFromStorage(sessionId);
    if (!loadedSession) {
      console.error(`Session ${sessionId} not found`);
      return false;
    }

    this._store.set(loadedSession);
    setActiveSession(sessionId);
    return true;
  }

  /**
   * Save current session to localStorage
   * Updates the updatedAt timestamp automatically
   */
  saveSession(): void {
    if (!this._session.id) {
      console.warn('Cannot save session without ID');
      return;
    }

    // Update timestamp before saving
    this._session.updatedAt = new Date().toISOString();
    saveSessionToStorage(this._session);
  }

  /**
   * Get current active scene
   */
  getCurrentScene(): SceneDefinition | null {
    if (!this._session.currentSceneId) return null;
    return this._session.scenes.find(s => s.id === this._session.currentSceneId) || null;
  }

  /**
   * Update current scene
   * @param sceneUpdate - Partial scene object with fields to update
   */
  updateCurrentScene(sceneUpdate: Partial<SceneDefinition>): void {
    this._store.update(session => {
      const sceneIndex = session.scenes.findIndex(s => s.id === session.currentSceneId);
      if (sceneIndex === -1) return session;

      const updatedScenes = [...session.scenes];
      updatedScenes[sceneIndex] = {
        ...updatedScenes[sceneIndex],
        ...sceneUpdate,
      };

      return {
        ...session,
        scenes: updatedScenes,
      };
    });
    this.saveSession();
  }

  /**
   * Add a new scene to the session
   * @param scene - The scene definition to add
   */
  addScene(scene: SceneDefinition): void {
    this._store.update(session => ({
      ...session,
      scenes: [...session.scenes, scene],
      currentSceneId: scene.id,
    }));
    this.saveSession();
  }

  /**
   * Complete current scene and add summary
   * @param summary - The scene summary
   */
  completeCurrentScene(summary: SceneSummary): void {
    const currentScene = this.getCurrentScene();
    if (!currentScene) return;

    this._store.update(session => {
      const sceneIndex = session.scenes.findIndex(s => s.id === session.currentSceneId);
      if (sceneIndex === -1) return session;

      const updatedScenes = [...session.scenes];
      updatedScenes[sceneIndex] = {
        ...updatedScenes[sceneIndex],
        status: 'summarized',
        completedAt: new Date().toISOString(),
        summary: summary.summary,
      };

      return {
        ...session,
        scenes: updatedScenes,
        storyContext: {
          ...session.storyContext,
          completedScenes: [...session.storyContext.completedScenes, summary],
        },
      };
    });
    this.saveSession();
  }

  /**
   * Add a new transcript entry
   * Enforces the 50 entry limit by removing oldest entries
   * @param entry - Transcript entry without id and timestamp (auto-generated)
   */
  addTranscriptEntry(entry: Omit<TranscriptEntry, 'id' | 't'>): void {
    const newEntry: TranscriptEntry = {
      id: generateUUID(),
      t: new Date().toISOString(),
      ...entry,
    };

    this._store.update(session => {
      const newTranscript = [...session.transcript, newEntry];
      
      // Enforce max transcript entries (trim oldest)
      if (newTranscript.length > MAX_TRANSCRIPT_ENTRIES) {
        const excess = newTranscript.length - MAX_TRANSCRIPT_ENTRIES;
        newTranscript.splice(0, excess);
      }

      return {
        ...session,
        transcript: newTranscript,
        totalTurns: session.totalTurns + 1,
        lastSpeaker: entry.speaker,
      };
    });

    this.saveSession();
  }

  /**
   * Add interaction to current scene
   * @param interaction - The interaction to add (without id and timestamp)
   */
  addSceneInteraction(interaction: Omit<SceneInteraction, 'id' | 'timestamp'>): void {
    const currentScene = this.getCurrentScene();
    if (!currentScene) return;

    const newInteraction: SceneInteraction = {
      id: generateUUID(),
      timestamp: new Date().toISOString(),
      ...interaction,
    };

    this._store.update(session => {
      const sceneIndex = session.scenes.findIndex(s => s.id === session.currentSceneId);
      if (sceneIndex === -1) return session;

      const updatedScenes = [...session.scenes];
      updatedScenes[sceneIndex] = {
        ...updatedScenes[sceneIndex],
        interactions: [...updatedScenes[sceneIndex].interactions, newInteraction],
      };

      return {
        ...session,
        scenes: updatedScenes,
        totalTurns: session.totalTurns + 1,
        lastSpeaker: interaction.speaker,
      };
    });
    this.saveSession();
  }

  /**
   * Add roll opportunity to current scene
   * @param opportunity - The roll opportunity to add
   */
  addRollOpportunity(opportunity: Omit<RollOpportunity, 'id' | 'resolved'>): RollOpportunity {
    const currentScene = this.getCurrentScene();
    if (!currentScene) throw new Error('No active scene');

    const newOpportunity: RollOpportunity = {
      id: generateUUID(),
      resolved: false,
      ...opportunity,
    };

    this._store.update(session => {
      const sceneIndex = session.scenes.findIndex(s => s.id === session.currentSceneId);
      if (sceneIndex === -1) return session;

      const updatedScenes = [...session.scenes];
      updatedScenes[sceneIndex] = {
        ...updatedScenes[sceneIndex],
        rollOpportunities: [...updatedScenes[sceneIndex].rollOpportunities, newOpportunity],
      };

      return {
        ...session,
        scenes: updatedScenes,
      };
    });
    this.saveSession();

    return newOpportunity;
  }

  /**
   * Resolve a roll opportunity
   * @param opportunityId - The ID of the opportunity to resolve
   * @param result - The dice roll result
   */
  resolveRollOpportunity(opportunityId: string, result: number): void {
    const currentScene = this.getCurrentScene();
    if (!currentScene) return;

    this._store.update(session => {
      const sceneIndex = session.scenes.findIndex(s => s.id === session.currentSceneId);
      if (sceneIndex === -1) return session;

      const updatedScenes = [...session.scenes];
      const scene = updatedScenes[sceneIndex];
      const oppIndex = scene.rollOpportunities.findIndex(o => o.id === opportunityId);
      
      if (oppIndex === -1) return session;

      const opportunity = scene.rollOpportunities[oppIndex];
      const updatedOpportunities = [...scene.rollOpportunities];
      updatedOpportunities[oppIndex] = {
        ...opportunity,
        resolved: true,
        result,
        success: result >= opportunity.difficulty,
      };

      updatedScenes[sceneIndex] = {
        ...scene,
        rollOpportunities: updatedOpportunities,
      };

      return {
        ...session,
        scenes: updatedScenes,
      };
    });
    this.saveSession();
  }

  /**
   * Mark session as completed and save
   */
  endSession(): void {
    this._store.update(session => ({
      ...session,
      status: 'completed' as const,
      updatedAt: new Date().toISOString(),
    }));
    this.saveSession();
    clearActiveSession();
  }

  /**
   * Resume active session on app start
   * Checks for active session ID and loads it
   * @returns true if an active session was resumed
   */
  resumeActiveSession(): boolean {
    const activeSessionId = getActiveSessionId();
    if (!activeSessionId) {
      return false;
    }

    return this.loadSession(activeSessionId);
  }

  /**
   * Clear current session (reset to default)
   */
  clearSession(): void {
    this._store.set({ ...defaultSession });
  }

  /**
   * Update session with partial data
   * @param updates - Partial session object with fields to update
   */
  updateSession(updates: Partial<Session>): void {
    this._store.update(session => ({
      ...session,
      ...updates,
    }));
    this.saveSession();
  }

  /**
   * Get session ID
   */
  getSessionId(): string {
    return this._session.id;
  }
  /**
   * Update story state
   * @param storyStateUpdate - Partial story state to update
   */
  updateStoryState(storyStateUpdate: Partial<StoryState>): void {
    this._store.update(session => ({
      ...session,
      storyState: {
        ...session.storyState,
        ...storyStateUpdate,
      },
    }));
    this.saveSession();
  }

  /**
   * Get story state
   */
  getStoryState(): StoryState {
    return this._session.storyState;
  }

  /**
   * Check if session is active
   */
  isActive(): boolean {
    return this._session.status === 'active';
  }

  /**
   * Update app state for resumption
   * @param appState - Partial app state to update
   */
  updateAppState(appState: Partial<Session['appState']>): void {
    this._store.update(session => ({
      ...session,
      appState: {
        turnState: session.appState?.turnState || 'idle',
        ...session.appState,
        ...appState,
        lastStateTimestamp: new Date().toISOString(),
      },
    }));
    this.saveSession();
  }

  /**
   * Get app state
   */
  getAppState(): Session['appState'] {
    return this._session.appState;
  }

  /**
   * Clear app state (reset to idle)
   */
  clearAppState(): void {
    this._store.update(session => ({
      ...session,
      appState: {
        turnState: 'idle',
      },
    }));
    this.saveSession();
  }
}

// Export singleton instance
export const sessionStore = new SessionStore();

// Export convenience functions
export const createSession = (theme: string, players: Player[]) =>
  sessionStore.createSession(theme, players);

export const loadSession = (sessionId: string) =>
  sessionStore.loadSession(sessionId);

export const saveSession = () =>
  sessionStore.saveSession();

export const getCurrentScene = () =>
  sessionStore.getCurrentScene();

export const updateCurrentScene = (sceneUpdate: Partial<SceneDefinition>) =>
  sessionStore.updateCurrentScene(sceneUpdate);

export const addScene = (scene: SceneDefinition) =>
  sessionStore.addScene(scene);

export const completeCurrentScene = (summary: SceneSummary) =>
  sessionStore.completeCurrentScene(summary);

export const addSceneInteraction = (interaction: Omit<SceneInteraction, 'id' | 'timestamp'>) =>
  sessionStore.addSceneInteraction(interaction);

export const addRollOpportunity = (opportunity: Omit<RollOpportunity, 'id' | 'resolved'>) =>
  sessionStore.addRollOpportunity(opportunity);

export const resolveRollOpportunity = (opportunityId: string, result: number) =>
  sessionStore.resolveRollOpportunity(opportunityId, result);

export const addTranscriptEntry = (entry: Omit<TranscriptEntry, 'id' | 't'>) =>
  sessionStore.addTranscriptEntry(entry);

export const endSession = () =>
  sessionStore.endSession();

export const resumeActiveSession = () =>
  sessionStore.resumeActiveSession();